# Generated by Django 5.0.6 on 2024-07-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_topic_room_host_alter_room_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
